name: wemake

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wemake-python-styleguide
        pip install aiogram
    - name: Analysing the code with wemake
      run: |
        flake8 --extend-ignore=D,WPS317,WPS326,WPS428,WPS202,E501,E303,I001,WPS318,WPS319 src/profbot.py src/test.py src/choice1.py src/choice2.py  
